In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
X,y = load_iris(return_X_y = True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train ,X_test , y_train , y_test = train_test_split(X,y,test_size = 0.3,random_state = 0)

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [8]:
### Practice on tips dataset

In [9]:
import seaborn as sns
df=sns.load_dataset('tips')

In [10]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
## time as target

X = df[['total_bill','tip', 'sex', 'smoker', 'day', 'size']]
y = df['time']

In [13]:
X

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [14]:
y

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [15]:
## Train Test Split

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.25 , random_state = 10)

In [16]:
X_train.head()

total_bill   tip   sex smoker  day  size
58        11.24  1.76  Male    Yes  Sat     2
1         10.34  1.66  Male     No  Sun     3
2         21.01  3.50  Male     No  Sun     3
68        20.23  2.01  Male     No  Sat     2
184       40.55  3.00  Male    Yes  Sun     2

In [17]:
# 1. Label encoding

from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()

X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])

In [18]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])

In [19]:
X_train

total_bill   tip  sex  smoker   day  size
58        11.24  1.76    1       1   Sat     2
1         10.34  1.66    1       0   Sun     3
2         21.01  3.50    1       0   Sun     3
68        20.23  2.01    1       0   Sat     2
184       40.55  3.00    1       1   Sun     2
..          ...   ...  ...     ...   ...   ...
64        17.59  2.64    1       0   Sat     3
15        21.58  3.92    1       0   Sun     2
228       13.28  2.72    1       0   Sat     2
125       29.80  4.20    0       0  Thur     6
9         14.78  3.23    1       0   Sun     2

[183 rows x 6 columns]

In [20]:
## One hot encoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('onehot',OneHotEncoder(drop = 'first'),[4])],remainder = 'passthrough')
import sys
import numpy as np
np.set_printoptions(threshold = sys.maxsize)
X_train = ct.fit_transform(X_train)

In [21]:
X_train

array([[ 1.  ,  0.  ,  0.  , 11.24,  1.76,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.23,  2.01,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 40.55,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 20.53,  4.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 41.19,  5.  ,  1.  ,  0.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 15.06,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.82,  1.75,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 26.88,  3.12,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 18.78,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.

In [22]:
X_test = ct.transform(X_test)
X_test

array([[ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  0.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.

In [26]:
## Label encoding of target y
le3 = LabelEncoder()
y_train = le3.fit_transform(y_train)

In [27]:
y_test = le3.transform(y_test)

In [29]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0])

In [28]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0])

In [30]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9672131147540983
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        43
           1       0.90      1.00      0.95        18

    accuracy                           0.97        61
   macro avg       0.95      0.98      0.96        61
weighted avg       0.97      0.97      0.97        61

[[41  2]
 [ 0 18]]


In [37]:
prediction = gnb.predict([[1.0,0.0,0.0,14.73,2.2,0.0,0.0,2.0]])
if prediction == 0:
    meal_time = "Dinner"
else:
    meal_time = "Lunch"

print(f"Predicted meal time: {meal_time}")

Predicted meal time: Dinner
